#!/bin/bash

set -e
set -u
set -o pipefail

function githubLatestTag {
    finalUrl=`curl https://github.com/$1/releases/latest -s -L -I -o /dev/null -w '%{url_effective}'`
    echo "${finalUrl##*v}"
}

platform=linux64
TAG=`githubLatestTag zyedidia/micro`

echo "Downloading https://github.com/zyedidia/micro/releases/download/v$TAG/micro-$TAG-"$platform".tar.gz"
curl -L "https://github.com/zyedidia/micro/releases/download/v$TAG/micro-$TAG-"$platform".tar.gz" > micro.tar.gz

tar -xvzf micro.tar.gz "micro-$TAG/micro"
install -D micro-$TAG/micro ./micro/usr/bin/micro

rm micro.tar.gz
rm -rf micro-$TAG

sed -i -e "s/VERSION/$TAG/g" ./micro/DEBIAN/control

dpkg-deb --build micro