#!/bin/bash

set -e
set -u
set -o pipefail

function getLatestTag {
    finalUrl=`curl https://github.com/$1/releases/latest -s -L -I -o /dev/null -w '%{url_effective}'`
    echo "${finalUrl##*v}"
}

declare -A archname
archname=([linux64]="amd64" [linux32]="i386" [linux-arm]="armhf")

function getArch {
	arch=`uname -p`
	case $arch in
		x86_64 | amd64)
			echo linux64
			;;
		
		x86 | i386 | i686)
			echo linux32
			;;
		armv7l)
			echo linux-arm
			;;
	esac
}

arch=`getArch`
tag=`getLatestTag zyedidia/micro`

tmpdir=`mktemp -d`
debdir="$tmpdir/DEBIAN"
bindir="$tmpdir/usr/bin"
mkdir "$debdir"
mkdir -p "$bindir"

cat << EOT > "$debdir/control"
Package: microeditor
Version: 
Architecture: ${archname[$arch]}
Maintainer: Vadim Velikodniy <vadim@velikodniy.name>
Section: text
Priority: optional
Homepage: https://github.com/zyedidia/micro
Description: Micro editor
  Micro is a terminal-based text editor that aims to be easy to use and intuitive, while also taking advantage of the full capabilities of modern terminals.
EOT

cat << EOT > "$debdir/postinst"
#!/bin/sh
set -e
if [ "\$1" = "configure" ] || [ "\$1" = "abort-upgrade" ]; then
    update-alternatives --install /usr/bin/editor editor /usr/bin/micro 50
fi
EOT
chmod +x "$debdir/postinst"

cat << EOT > "$debdir/prerm"
#!/bin/sh
set -e
if [ "\$1" != "upgrade" ]; then
    update-alternatives --remove editor /usr/bin/micro
fi
EOT
chmod +x "$debdir/prerm"

curl -L "https://github.com/zyedidia/micro/releases/download/v$tag/micro-$tag-$arch.tar.gz" > "$tmpdir/micro.tar.gz"
tar -xvzf "$tmpdir/micro.tar.gz" -C "$bindir" --strip-components 1 "micro-$tag/micro"
rm "$tmpdir/micro.tar.gz"

sed -i -e "s/^Version:.*/Version: $tag/g" "$debdir/control"

dpkg-deb --build "$tmpdir" "micro_${tag}_${archname[$arch]}.deb"

rm -rf "$tmpdir"